name: 02-02-Schedule-Job
# on: workflow_dispatch
on: 
  schedule:
    - cron:  '5 4 * * *'
jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bye World"
