name: 02-02-Simple Workflow
# on: workflow_dispatch
on: 
  schedule:
    - cron:  '*/5 * * * *'
jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bye World"
