name: 05-01-actions
on: workflow_dispatch
jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-java@4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'